### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by peppapiggyme** [peppapiggyme/bbtautau-hists#1]
- [x] draw signal
- [x] blinding (all)
- [x] blinding (criteria)
- [x] colors
- [x] binnings
- [x] redesign `Config` -> update is not useful as ps are changed after `manipulate()`
- [x] systematic histograms
- [x] systematic plotting
- [x] comparison plots
- [x] yields
- [ ] root drawables
- [ ] Component classes are so similar (polymorphise) yes
- [x] systematics in drawStack
- [x] possibility to convert the Examples into kinda "scriptable language"
- [x] workspace tool
- [x] pulls
- [x] ranking (post-fit)
- [x] Automatic optimized Mva re-binning
- [x] Automatic re-binning with quantile
- [x] Fit binning
- [x] Documentation (Doxygen)
- [x] Fit binning from file
- [x] Pseudodata fitting -> significance ntuple
- [x] sorting of process for legend (done by anomolous eProcess)
- [x] Process scale factors must be provided by user (a hash table
- [x] Postfit plotting
- [x] Improvement of configuration
- [ ] Split headers and sources of the core tools

**Comment by peppapiggyme** [comment]
will be addressed in https://github.com/peppapiggyme/opaque
